name: "S3 - Sub-project: Single Run"
run-name: "Sub-project: Single Run (${{inputs.RESOURCE}}): ${{inputs.ACTION == 'd' && 'Destroy' || 'Create'}}"

on: 
  workflow_dispatch:
    inputs:
      RESOURCE:
        required: true
        type: string
        description: "Resource Id. ex: 2a, 2c, 3a"
      ACTION:
        required: false
        type: string
        description: "d = Destroy | Outros = Create"
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."
  workflow_call:
    inputs:
      RESOURCE:
        required: true
        type: string
        description: "Resource Id. ex: 2a, 2c, 3a"
      ACTION:
        required: false
        type: string
        description: "d = Destroy | Outros = Create"

env:
  AWS_ACCESS_KEY_ID: ${{ vars.IAM_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.IAM_AWS_SECRET_ACCESS_KEY }}  

jobs:
  action:    
    name: "${{inputs.ACTION == 'd' && 'destroy' || 'create'}} (${{inputs.RESOURCE}})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Terraform Apply
      - name: Terraform Apply
        if: ${{ inputs.ACTION != 'd' }}
        run: |
          ./apply.sh ${{ inputs.RESOURCE }}

      # Terraform Apply
      - name: Terraform Destroy
        if: ${{ inputs.ACTION == 'd' }}
        run: |
          ./destroy.sh ${{ inputs.RESOURCE }}