name: "C1 - Whole project: Create"
run-name: "C1 - Whole project: Create"

on: 
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

## ---------------------------------------------------------------------------------------------------------------------
## Create project 
## ---------------------------------------------------------------------------------------------------------------------
jobs:
  ## - Camada 1 --------------------------------------------------------------------------------------------------------

  vpc:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '01a'
    secrets: inherit

  nat_gateway:
    needs: [
      vpc
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '01a1'
    secrets: inherit

  acm:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '01b'
    secrets: inherit

  cloudwatch_logs:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '01c'
    secrets: inherit
  
  ecr:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '01d'
    secrets: inherit

  ses:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '01e'
    secrets: inherit

  ## - Camada 2 --------------------------------------------------------------------------------------------------------

  elb:
    needs: [
      vpc, nat_gateway, acm, cloudwatch_logs, ecr, ses
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '02a'
    secrets: inherit

  rds:
    needs: [
      vpc, nat_gateway, acm, cloudwatch_logs, ecr, ses
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '02b'
    secrets: inherit

  efs:
    needs: [
      vpc, nat_gateway, acm, cloudwatch_logs, ecr, ses
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '02c'
    secrets: inherit

  container_image_builder:
    needs: [
      vpc, nat_gateway, acm, cloudwatch_logs, ecr, ses
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '02d'
    secrets: inherit

  ## - Camada 3 --------------------------------------------------------------------------------------------------------

  ecs:
    needs: [
      elb, rds, efs, container_image_builder
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '03a'
    secrets: inherit

  ## - Camada 4 --------------------------------------------------------------------------------------------------------

  container_image_deploy:
    needs: [
      ecs
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '04a'
    secrets: inherit

  ## -------------------------------------------------------------------------------------------------------------------