name: "D1 - Whole project: Destroy"
run-name: "D1 - Whole project: Destroy"

on:
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

jobs:
  ## - Ferramentas de desenvolvimento ----------------------------------------------------------------------------------
  vpc_endpoint_ssm:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "5a"
      ACTION: "d"
    secrets: inherit

  bastion:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "5a"
      ACTION: "d"
    secrets: inherit

  ## - Camada 5 --------------------------------------------------------------------------------------------------------
  container_image_deploy:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "5a"
      ACTION: "d"
    secrets: inherit

  ## - Camada 4 --------------------------------------------------------------------------------------------------------

  ecs:
    needs: [container_image_deploy]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "4a"
      ACTION: "d"
    secrets: inherit

  ## - Camada 3 --------------------------------------------------------------------------------------------------------

  elb:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "3a"
      ACTION: "d"
    secrets: inherit

  rds:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "3b"
      ACTION: "d"
    secrets: inherit

  efs:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "3c"
      ACTION: "d"
    secrets: inherit

  container_image_builder:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "3d"
      ACTION: "d"
    secrets: inherit
  
  ## - Camada 2 --------------------------------------------------------------------------------------------------------
  
  nat_gateway:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "2a1"
      ACTION: "d"
    secrets: inherit

  vpc:
    needs: [
      vpc_endpoint_ssm, bastion,
      elb, rds, efs, container_image_builder, nat_gateway
      ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "2a"
      ACTION: "d"
    secrets: inherit

  acm:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "2b"
      ACTION: "d"
    secrets: inherit

  cloudwatch_logs:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "2c"
      ACTION: "d"
    secrets: inherit

  ecr:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "2d"
      ACTION: "d"
    secrets: inherit

  ses:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "2e"
      ACTION: "d"
    secrets: inherit

  ## - Camada 1 --------------------------------------------------------------------------------------------------------

  github_sync:
    needs: [vpc, nat_gateway, acm, cloudwatch_logs, ecr, ses]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "1a"
      ACTION: "d"
    secrets: inherit

  ## -------------------------------------------------------------------------------------------------------------------
