name: "C1 - Whole project: Create"
run-name: "C1 - Whole project: Create"

on: 
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

jobs:
  ################################# 
  ######## Create project #########
  #################################
  github_sync:
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '1a'
    secrets: inherit

  vpc_app:
    needs: [
      github_sync
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2a'
    secrets: inherit

  acm_app:
    needs: [
      github_sync
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2c'
    secrets: inherit

  rds_app:
    needs: [
      github_sync, 
      vpc_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3b'
    secrets: inherit

  efs_app:
    needs: [
      github_sync, 
      vpc_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3c'
    secrets: inherit

  image_builder_app:
    needs: [
      github_sync,
      vpc_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '4c'
    secrets: inherit

  ami_app:
    needs: [
      github_sync,
      vpc_app,
      image_builder_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '5a'
    secrets: inherit

  elb_app:
    needs: [
      github_sync,
      vpc_app, acm_app,
      rds_app, efs_app,
      ami_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '6a'
    secrets: inherit

  vpc_endpoint_codedeploy:
    needs: [
      github_sync,
      vpc_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '7a'
    secrets: inherit
    
  vpc_endpoint_s3:
    needs: [
      github_sync,
      vpc_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '7b'
    secrets: inherit

  vpc_endpoint_ssm:
    needs: [
      github_sync,
      vpc_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '7c'
    secrets: inherit    

  deploy_app:
    needs: [
      github_sync,
      vpc_app,
      rds_app,
      elb_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '8a'
    secrets: inherit