name: "D1 - Whole project: Destroy"
run-name: "D1 - Whole project: Destroy"

on:
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

jobs:
  ## - Ferramentas de desenvolvimento ----------------------------------------------------------------------------------
  
  bastion:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "dev_a"
      ACTION: "d"
    secrets: inherit

  vpc_endpoint_ssm:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "dev_b"
      ACTION: "d"
    secrets: inherit 

  ## - Camada 4 --------------------------------------------------------------------------------------------------------
  container_image_deploy:
    needs: []
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "04a"
      ACTION: "d"
    secrets: inherit

  ## - Camada 3 --------------------------------------------------------------------------------------------------------

  ecs:
    needs: [container_image_deploy]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "03a"
      ACTION: "d"
    secrets: inherit

  ## - Camada 2 --------------------------------------------------------------------------------------------------------

  elb:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "02a"
      ACTION: "d"
    secrets: inherit

  rds:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "02b"
      ACTION: "d"
    secrets: inherit

  efs:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "02c"
      ACTION: "d"
    secrets: inherit

  container_image_builder:
    needs: [ecs]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "02d"
      ACTION: "d"
    secrets: inherit
  
  ## - Camada 1 --------------------------------------------------------------------------------------------------------
  
  nat_gateway:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01a1"
      ACTION: "d"
    secrets: inherit

  vpc_gateway_endpoints:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01a2"
      ACTION: "d"
    secrets: inherit

  vpc_interface_endpoints:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01a3"
      ACTION: "d"
    secrets: inherit

  vpc:
    needs: [
      vpc_endpoint_ssm, bastion,
      nat_gateway, vpc_gateway_endpoints, vpc_interface_endpoints,
      elb, rds, efs, container_image_builder, 
      ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01a"
      ACTION: "d"
    secrets: inherit

  acm:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01b"
      ACTION: "d"
    secrets: inherit

  cloudwatch_logs:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01c"
      ACTION: "d"
    secrets: inherit

  ecr:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01d"
      ACTION: "d"
    secrets: inherit

  ses:
    needs: [elb, rds, efs, container_image_builder]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: "01e"
      ACTION: "d"
    secrets: inherit

  ## - Parameter Store --------------------------------------------------------------------------------------------------------

  parameter_store:
    needs: [vpc, nat_gateway, acm, cloudwatch_logs, ecr, ses]
    uses: ./.github/workflows/sync-parameter-store.yml
    with:
      ACTION: "d"
    secrets: inherit

  ## -------------------------------------------------------------------------------------------------------------------
