name: "C1 - Whole project: Create"
run-name: "C1 - Whole project: Create"

on: 
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

## -----------------------------------------------------------------------------
## Create project 
## -----------------------------------------------------------------------------
jobs:
  ## - Nivel 1 -----------------------------------------------------------------

  github_sync:
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '1a'
    secrets: inherit

  ## - Nivel 2 -----------------------------------------------------------------

  vpc:
    needs: [
      github_sync
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2a'
    secrets: inherit

  nat_gateway:
    needs: [
      github_sync,
      vpc
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2a1'
    secrets: inherit

  acm:
    needs: [
      github_sync
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2b'
    secrets: inherit

  cloudwatch_logs:
    needs: [
      github_sync
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2c'
    secrets: inherit
  
  ecr:
    needs: [
      github_sync
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2d'
    secrets: inherit

  ## - Nivel 3 -----------------------------------------------------------------

  elb:
    needs: [
      vpc,
      acm
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3a'
    secrets: inherit

  rds:
    needs: [
      vpc
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3b'
    secrets: inherit

  efs:
    needs: [
      
      vpc
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3c'
    secrets: inherit

  container_image_builder:
    needs: [
      ecr,
      elb
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3d'
    secrets: inherit    

  ## - Nivel 4 -----------------------------------------------------------------

  ecs:
    needs: [
      vpc,
      ecr,
      elb, rds, efs
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '4a'
    secrets: inherit

  ## - Nivel 5 -----------------------------------------------------------------

  container_image_deploy:
    needs: [
      elb,
      ecs
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '5a'
    secrets: inherit

  ## ---------------------------------------------------------------------------